image:https://travis-ci.org/spidermonkey/topologicalOrder.svg?branch=master["Build Status", link="https://travis-ci.org/spidermonkey/topologicalOrder"]

== Simple topological order generator on cyclic inverse dependency graphs.

== Building from Source
The application can be easily built with the
https://github.com/takari/maven-wrapper[maven wrapper]. You also need JDK 1.8.

[indent=0]
----
	$ ./mvnw clean install
----

If you want to build with the regular `mvn` command, you will need
http://maven.apache.org/run-maven/index.html[Maven v3.2.1 or above].

NOTE: You may need to increase the amount of memory available to Maven by setting
a `MAVEN_OPTS` environment variable with the value `-Xmx512m`.

NOTE: To compile/work with the code in your IDE you most probably need to install Lombok plugin.

== Running tests

[indent=0]
----
	$ ./mvnw test
----

The regular `mvn` command can also be used.

== Design Considerations

I've used a well known algorithm to calculate node order:
https://link.springer.com/article/10.1007%2FBF00268499[Tarjan, Robert E. (1976), "Edge-disjoint spanning trees and depth-first search", Acta Informatica, 6 (2): 171–185]

Depth first search is implemented as a reusable component using the visitor pattern.

== License
Open Source software released under the
http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].

